### ISSUE TITLE
feat: Add an About page

### ISSUE THREAD

**Issue by adxy** [adxy/chesskhelo.in#1]
The footer link of the about page points to the home page.

It's nice to have an about page letting the community know about the project. 

Read this article to get inspiration about the content of the page: https://www.adxy.dev/projects/chesskhelo

A good example of an about page would be - https://lichess.org/about

Interested to add this? Comment & I'll assign this to you.

**Comment by cjiayu03** [comment]
Hello, I am interested in this.

**Comment by adxy** [comment]
@c00kie123 assigned it to you!🙌

**Comment by cjiayu03** [comment]
Hey, thanks for the assignment. This is my first time contributing, so I would like some clarification before I start. I understand you would like to create a new page for the About Page.
Can I confirm that my tasks would be adding in "about.jsx" in directory of "chesskhello.in/pages" as well as adding in the url in "footer.jsx" in the directory of "chesskhelo.in/compenents/Layout/Footer.jsx"?

Let me know if I am missing out on anything!

**Comment by adxy** [comment]
> Hey, thanks for the assignment. This is my first time contributing, so I would like some clarification before I start. I understand you would like to create a new page for the About Page. Can I confirm that my tasks would be adding in "about.jsx" in directory of "chesskhello.in/pages" as well as adding in the url in "footer.jsx" in the directory of "chesskhelo.in/compenents/Layout/Footer.jsx"?
> 
> Let me know if I am missing out on anything!

You got it right. You'll also have to add content for the about page, we can discuss on whatever you come up with. 

And for raising a pull request would be. 
1. Fork this repository. (You should start with this, if you've directly cloned the repository)
2. Clone the forked repository in your device with git clone.
3. Create a new branch. You can name it like this. [username]:[IssueId] For you the branch will be - c00kie123:1
4. Push this branch to your GitHub repo "git push origin c00kie123:1" 
5. Create a pull request. 

Just realised I'll have to add the above steps to the contribution guidelines. 😄

Let me know if you'll need help with anything.

**Comment by cjiayu03** [comment]
Hey i have created the PR. Look at it and let me know!

**Comment by adxy** [comment]
> Hey i have created the PR. Look at it and let me know!

Hey thanks for your contribution, I'll take a look at it soon.

**Comment by cjiayu03** [comment]
Hey , any updates?
