### ISSUE TITLE
No check sound

### ISSUE THREAD

**Issue by adxy** [adxy/chesskhelo.in#3]
There's no check sound when the opponent gives a check.

**Comment by adityadafe** [comment]
Hello @adxy im kinda new to open source and development but I am willing to contribute to this issue do you mind helping me to solve this issue ?

**Comment by adxy** [comment]
Sure @KaKashi1210 . Try to run this on your local machine first. And get familiar with the app. Meanwhile, I'll try to add contributions guidelines by tomorrow's EOD. That will help you get started with your contribution.

Feel free to ask anything if you'd like. Also, fork this and clone the forked repo to your local machine instead of this. 

I've assigned this issue to you.

**Comment by adxy** [comment]
Closed in favour of 9e903588184651d9e9fc5e7342c66f089aa64990
