### ISSUE TITLE
Add contribution guide page

### ISSUE THREAD

**Issue by cjiayu03** [adxy/chesskhelo.in#8]
Hey, I noticed the contribution guide page is missing! Do you want to add in it? I can help with it

**Comment by adxy** [comment]
Sure, we can start with a google doc. Can you create and draft one? We can finalise the content on the doc and then add this.

**Comment by adxy** [comment]
@c00kie123 since, I've not heard from you in a while I'll self assign this.

**Comment by adxy** [comment]
Closed in favour of: 1e5e118254ebefd3ac80be04a0f61dc81edebadc
